name: HelloWorld
version: 1.0.0
main: io.github.itshaithamn.infection.Main
api-version: 1.20

commands:
  infection:
    description: Starts the infection gamemode
    aliases:
      - infected
      - zombies
      - i

permissions:
  infection.command.infected:
    description: Allows the player to use the /infected command.
    default: op
  infection.command.team:
    description: Allows the player to add players to teams using /infected team.
    default: op
  infection.command.rmteam:
    description: Allows the player to remove players from teams using /infected rmteam.
    default: op
  infection.command.list:
    description: Allows the player to list players in a team using /infected list.
    default: true